baseURL = "https://juanitodread.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
metaDataFormat = "toml"
contentDir = "content"
publishDir = "public"
buildDrafts = false
title = "@juanitodread"
theme = "hugo-coder"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

paginate = 10
canonifyurls = true
enableEmoji = true

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table,linenostart=1"

disqusShortname = "juanitodread"

[indexes]
    category = "categories"
    tag = "tags"
[params]
    author = "• Juan Sandoval •"
    info = "Software Developer Engineer"
    description = "Juan Sandoval's personal website"
    keywords = "blog,developer,personal"
    avatarURL = "/images/me.jpg"
    since = 2015

    dateFormat = "January 2, 2006"

    footerContent = ""

    hideFooter = false
    hideCredits = true
    hidecopyright = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    rtl = false
    math = false

    # Enable Twemoji
    enableTwemoji = true

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/post/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/pages/cv"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/juanitodread/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/juanitodread/"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-stack-overflow"
    weight = 4
    url = "https://stackoverflow.com/users/362937/juanitodread"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@juanitodread"
[[params.social]]
    name = "Flickr"
    icon = "fab fa-flickr"
    weight = 6
    url = "https://www.flickr.com/photos/juanitodread/"
